version: "3.1"
services:

  db:
    image: mysql:8.0
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=money
      - MYSQL_USER=test
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "12007:3306"
    network_mode: bridge

  webserver:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "12002:80"
    links:
      - php
    network_mode: bridge

  php:
    build: docker/php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    links:
      - db
    network_mode: bridge